// <auto-generated />
using System;
using Filippov_Georgy_KT_31_21.DepartmentService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filippov_Georgy_KT_31_21.DepartmentService.Migrations
{
    [DbContext(typeof(DepartmentsDbContext))]
    [Migration("20250110102128_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Filippov_Georgy_KT_31_21.DepartmentService.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadId")
                        .HasColumnType("integer")
                        .HasColumnName("f_head_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("c_name");

                    b.HasKey("Id")
                        .HasName("pk_cs_department_department_id");

                    b.ToTable("cs_department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoundationDate = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadId = 1,
                            Name = "Кафедра математики"
                        },
                        new
                        {
                            Id = 2,
                            FoundationDate = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadId = 2,
                            Name = "Кафедра физики"
                        },
                        new
                        {
                            Id = 3,
                            FoundationDate = new DateTime(1950, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadId = 3,
                            Name = "Кафедра информатики"
                        },
                        new
                        {
                            Id = 4,
                            FoundationDate = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeadId = 4,
                            Name = "Кафедра философии"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
